version: 2
updates:
  - package-ecosystem: pip
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: daily
    commit-message:
        prefix: "chore(deps): update dependency"
