default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.271
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
      language_version: python3.11
