default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.275'
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/ambv/black
    rev: '23.3.0'
    hooks:
    - id: black
      language_version: python3.11
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML]
        exclude: ^tests/