name: Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Configure cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-publish-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        python -m pip install poetry
        python -m poetry  self add poetry-dynamic-versioning
        python -m poetry install
    - name: Run build
      run: |
          python -m poetry build
    - name: Run publish
      run: |
          poetry publish --username __token__ --password "${PYPI_TOKEN}"
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
